[package]
name = "cli"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
crossterm = "0.27.0"
rayon = "1.8.1"
