name: Pull request Check
on:   
    pull_request:

jobs:   
    check_and_test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true
            - name: Run cargo check
              run: cargo check
            - name: Run cargo test
              run: cargo test
            - name: Check Rust formatting
              run: cargo fmt -- --check