name: Publish CLI
on:
  push:
    branches:
      - 'Stable'
      - 'Alpha'
      - 'Beta'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pycompile click
          
        
      - name: Run compile script
        run: python compile.py
        
      - name: Verify compiled files
        run: |
          if [ ! -f dist/eve ]; then
            echo "Error: eve executable not found."
            exit  1
          fi
          if [ ! -f dist/eve.ps1 ]; then
            echo "Error: eve.ps1 script not found."
            exit  1
          fi
          if [ ! -f dist/eve.pyc ]; then
            echo "Error: eve.pyc bytecode not found."
            exit  1
          fi
          echo "All compiled files are present."


  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
        # Debuging
      - name: List all files in dist
        run: ls -la ./dist
        
      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: Eve-Cli_Output
          path: ./dist